EPAM.RDPreEducationPortal.Web.Site/Models/CandidateDetails.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EPAM.RDPreEducationPortal.Web.Site.Models
{
    public class CandidateDetails : BaseClass
    {
        public string FirstRoundCodingMarks { get; set; }
        public string PreviousAssessment { get; set; }

        public string Status { get; set; }
        public string SecondRoundMarks { get; set; }
        public int TRScore { get; set; }
        public string TRInterviewer { get; set; }
        public int GDStatus{ get; set; }
    }
}

EPAM.RDPreEducationPortal.Web.Site/Controllers/CandidateDetailsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.OleDb;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Xml;
using EPAM.RDPreEducationPortal.Utilities;
using EPAM.RDPreEducationPortal.Web.Site.EntityFramework;
using EPAM.RDPreEducationPortal.Web.Site.Models;

namespace EPAM.RDPreEducationPortal.Web.Site.Controllers
{
    public class CandidateDetailsController : Controller
    {
        private readonly Candidate_Details _model = new Candidate_Details();
        private EpamRDPreEducationEntities db = new EpamRDPreEducationEntities();

        // GET: CandidateDetails
        public ActionResult Index(bool? successMessage)
        {
            if (successMessage != null && successMessage == true)
            {
                _model.SuccessMessage = "Feedback Recorded successfully.";
            }
            //db.Candidate_Details.ToList()
            return View(_model);
        }
        // GET: CandidateDetails/HREligible
        public ActionResult HREligible()
        {
            DataSet ds = SqlHelper.FillDataSet(ConfigurationManager.RdConnectionString, "Get_Candidate_Details_HREligible");
            var myData = ds.Tables[0].AsEnumerable().Select(r => new Candidate_Details
            {
                CandidateID = r.Field<int>("CandidateID"),
                CandidateName = r.Field<string>("CandidateName"),
                EmailAddress = r.Field<string>("CandidateEmail"),
                Gender = r.Field<string>("Gender"),
                //MarksScored = r.Field<double>("MarksScored"),
                FirstRoundCodingMarks = r.Field<string>("FirstRoundMarks"),
                MobileNumber = r.Field<string>("MobileNumber"),
                Status = r.Field<string>("Status"),
                SecondRoundMarks = r.Field<string>("SecondRoundMarks"),
                TestId = r.Field<int>("TestId"),
                TRInterviewer = r.Field<string>("TRInterviewer"),
                TRScore = r.Field<int>("TRScore"),
                PermanentStateOfResidence = r.Field<string>("PermanentStateOfResidence")
            });
            var s = myData.ToList();
            return View(s);
        }
        // GET: CandidateDetails/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Candidate_Details candidate_Details = db.Candidate_Details.Find(id);
            if (candidate_Details == null)
            {
                return HttpNotFound();
            }
            return View(candidate_Details);
        }

        // GET: CandidateDetails
        public ActionResult List(int? testId)
        {
            var role = "";
            if (Session["Role"] != null)
            {
                role = Session["Role"].ToString();
            }
            AccountModel accountModel = new AccountModel();
            if (Session["UserDetails"] != null)
            {
                accountModel = (AccountModel)Session["UserDetails"];
            }

            if (accountModel.Role == "TechnicalInterviewer" || accountModel.Role == "GDManager")
            {
                var parameters = new SqlParameter[2];
                parameters[0] = new SqlParameter("@TestId", testId);
                parameters[1] = new SqlParameter("@Role", role);
                DataSet ds = SqlHelper.FillDataSet(ConfigurationManager.RdConnectionString, "Get_Candidate_Details", parameters);
                var myData = ds.Tables[0].AsEnumerable().Select(r => new Candidate_Details
                {
                    CandidateID = r.Field<int>("CandidateID"),
                    CandidateName = r.Field<string>("CandidateName"),
                    EmailAddress = r.Field<string>("CandidateEmail"),
                    Gender = r.Field<string>("Gender"),
                    //MarksScored = r.Field<double>("MarksScored"),
                    FirstRoundCodingMarks = r.Field<string>("FirstRoundMarks"),
                    MobileNumber = r.Field<string>("MobileNumber"),
                    Status = r.Field<string>("Status"),
                    SecondRoundMarks = r.Field<string>("SecondRoundMarks"),
                    TestId = r.Field<int>("TestId"),
                    TRInterviewer = r.Field<string>("TRInterviewer"),
                    //TRScore = r.Field<int>("TRScore"),
                    PermanentStateOfResidence = r.Field<string>("PermanentStateOfResidence"),
                    GDStatus = r.Field<int>("GDStatus")
                });
                var s = myData.ToList();
                return View(s);
            }
            else if (accountModel.Role == "HR")
            {
                var parameters = new SqlParameter[1];
                parameters[0] = new SqlParameter("@TestId", testId);
                DataSet ds = SqlHelper.FillDataSet(ConfigurationManager.RdConnectionString, "Get_Candidate_Details_HREligible", parameters);
                var myData = ds.Tables[0].AsEnumerable().Select(r => new Candidate_Details
                {
                    CandidateID = r.Field<int>("CandidateID"),
                    CandidateName = r.Field<string>("CandidateName"),
                    EmailAddress = r.Field<string>("CandidateEmail"),
                    Gender = r.Field<string>("Gender"),
                    //MarksScored = r.Field<double>("MarksScored"),
                    FirstRoundCodingMarks = r.Field<string>("FirstRoundMarks"),
                    MobileNumber = r.Field<string>("MobileNumber"),
                    Status = r.Field<string>("Status"),
                    SecondRoundMarks = r.Field<string>("SecondRoundMarks"),
                    TestId = r.Field<int>("TestId"),
                    TRInterviewer = r.Field<string>("TRInterviewer"),
                    TRScore = r.Field<int>("TRScore"),
                    PermanentStateOfResidence = r.Field<string>("PermanentStateOfResidence")
                });
                var s = myData.ToList();
                return View("HREligible", s);
            }
            return null;
        }

        // GET: CandidateDetails/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CandidateDetails/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CandidateID,CandidateName,CandidateLocationID,CandidateEmail,ContactNumber,CandidateResume,StartedOn,StartingTime,PreviousAssessments,Duration,MarksScored,Result,Report,PublicReport,FirstName,LastName,EmailAddress,MobileNumber,GraduationCollegeName,Graduation,GraduationSpecialty,YearOfPassedOut,GraduationMarksCGPA,C12MarksCGPA,C10MarksCGPA,Gender,PermanentAddress,PermanentStateOfResidence,CurrentAddress,GovernmentIssuedIDProof,PreferredJobLocation")] Candidate_Details candidate_Details)
        {
            if (ModelState.IsValid)
            {
                db.Candidate_Details.Add(candidate_Details);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(candidate_Details);
        }

        // GET: CandidateDetails/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Candidate_Details candidate_Details = db.Candidate_Details.Find(id);
            if (candidate_Details == null)
            {
                return HttpNotFound();
            }
            return View(candidate_Details);
        }

        // POST: CandidateDetails/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CandidateID,CandidateName,CandidateLocationID,CandidateEmail,ContactNumber,CandidateResume,StartedOn,StartingTime,PreviousAssessments,Duration,MarksScored,Result,Report,PublicReport,FirstName,LastName,EmailAddress,MobileNumber,GraduationCollegeName,Graduation,GraduationSpecialty,YearOfPassedOut,GraduationMarksCGPA,C12MarksCGPA,C10MarksCGPA,Gender,PermanentAddress,PermanentStateOfResidence,CurrentAddress,GovernmentIssuedIDProof,PreferredJobLocation,CreatedBy,LastEditedBy")] Candidate_Details candidate_Details)
        {
            if (ModelState.IsValid)
            {
                db.Entry(candidate_Details).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(candidate_Details);
        }

        // GET: CandidateDetails/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Candidate_Details candidate_Details = db.Candidate_Details.Find(id);
            if (candidate_Details == null)
            {
                return HttpNotFound();
            }
            return View(candidate_Details);
        }

        // POST: CandidateDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Candidate_Details candidate_Details = db.Candidate_Details.Find(id);
            db.Candidate_Details.Remove(candidate_Details);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

EPAM.RDPreEducationPortal.Web.Site/Controllers/Candidate_DetailsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EPAM.RDPreEducationPortal.Web.Site.EntityFramework;

namespace EPAM.RDPreEducationPortal.Web.Site.Controllers
{
    public class Candidate_DetailsController : Controller
    {
        private EpamRDPreEducationEntities db = new EpamRDPreEducationEntities();

        // GET: Candidate_Details
        public ActionResult Index()
        {
            return View(db.Candidate_Details.ToList());
        }

        // GET: Candidate_Details/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Candidate_Details candidate_Details = db.Candidate_Details.Find(id);
            if (candidate_Details == null)
            {
                return HttpNotFound();
            }
            return View(candidate_Details);
        }

        // GET: Candidate_Details/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Candidate_Details/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CandidateID,CandidateName,CandidateLocationID,CandidateEmail,ContactNumber,CandidateResume,StartedOn,StartingTime,PreviousAssessments,Duration,MarksScored,Result,Report,PublicReport,FirstName,LastName,EmailAddress,MobileNumber,GraduationCollegeName,Graduation,GraduationSpecialty,YearOfPassedOut,GraduationMarksCGPA,C12MarksCGPA,C10MarksCGPA,Gender,PermanentAddress,PermanentStateOfResidence,CurrentAddress,GovernmentIssuedIDProof,PreferredJobLocation,RecruitmentId,TestId,SecondRoundPublicReport,IsPEPStudent,IsCodathonWinner,IsGDCleared,GDComments,PreferredLocationForSecondRound")] Candidate_Details candidate_Details)
        {
            if (ModelState.IsValid)
            {
                db.Entry(candidate_Details).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(candidate_Details);
        }

        // GET: Candidate_Details/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Candidate_Details candidate_Details = db.Candidate_Details.Find(id);
            if (candidate_Details == null)
            {
                return HttpNotFound();
            }
            return View(candidate_Details);
        }

        // POST: Candidate_Details/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CandidateID,CandidateName,CandidateLocationID,CandidateEmail,ContactNumber,CandidateResume,StartedOn,StartingTime,PreviousAssessments,Duration,MarksScored,Result,Report,PublicReport,FirstName,LastName,EmailAddress,MobileNumber,GraduationCollegeName,Graduation,GraduationSpecialty,YearOfPassedOut,GraduationMarksCGPA,C12MarksCGPA,C10MarksCGPA,Gender,PermanentAddress,PermanentStateOfResidence,CurrentAddress,GovernmentIssuedIDProof,PreferredJobLocation,RecruitmentId,TestId,SecondRoundPublicReport,IsPEPStudent,IsCodathonWinner,IsGDCleared,GDComments,PreferredLocationForSecondRound")] Candidate_Details candidate_Details)
        {
            if (ModelState.IsValid)
            {
                db.Entry(candidate_Details).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(candidate_Details);
        }

        // GET: Candidate_Details/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Candidate_Details candidate_Details = db.Candidate_Details.Find(id);
            if (candidate_Details == null)
            {
                return HttpNotFound();
            }
            return View(candidate_Details);
        }

        // POST: Candidate_Details/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Candidate_Details candidate_Details = db.Candidate_Details.Find(id);
            db.Candidate_Details.Remove(candidate_Details);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EPAM.RDPreEducationPortal.Web.Site/Views/CandidateDetails/Delete.cshtml
@model EPAM.RDPreEducationPortal.Web.Site.EntityFramework.Candidate_Details

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Candidate_Details</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CandidateName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CandidateName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CandidateLocationID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CandidateLocationID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CandidateEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CandidateEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContactNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CandidateResume)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CandidateResume)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartedOn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartedOn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartingTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartingTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PreviousAssessments)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PreviousAssessments)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Duration)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Duration)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MarksScored)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MarksScored)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Result)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Result)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Report)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Report)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PublicReport)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PublicReport)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmailAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmailAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MobileNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MobileNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GraduationCollegeName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GraduationCollegeName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Graduation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Graduation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GraduationSpecialty)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GraduationSpecialty)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.YearOfPassedOut)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.YearOfPassedOut)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GraduationMarksCGPA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GraduationMarksCGPA)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.C12MarksCGPA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.C12MarksCGPA)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.C10MarksCGPA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.C10MarksCGPA)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PermanentAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PermanentAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PermanentStateOfResidence)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PermanentStateOfResidence)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CurrentAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CurrentAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GovernmentIssuedIDProof)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GovernmentIssuedIDProof)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PreferredJobLocation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PreferredJobLocation)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

EPAM.RDPreEducationPortal.Web.Site/Views/CandidateDetails/UploadCandidates.cshtml
@model EPAM.RDPreEducationPortal.Web.Site.EntityFramework.Candidate_Details

@{
    ViewBag.Title = "UploadCandidates";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <h2>Upload Candidates</h2>

    @using (Html.BeginForm("UploadCandidates", "CandidateDetails", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
    <div class="form-horizontal">
        <hr />
        @if (!string.IsNullOrEmpty(Model.SuccessMessage))
        {
            <div class="alert alert-success" role="alert">
                <strong>Well done!</strong> @Model.SuccessMessage.
            </div>
        }
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label>Recruitment</label>
            @Html.DropDownListFor(model => model.RecruitmentId, new SelectList(Enumerable.Empty<SelectListItem>(), "RecruitmentId", "Name"), new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.RecruitmentId, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            <label>Test Hosted</label>
            @Html.DropDownListFor(model => model.TestId, new SelectList(Enumerable.Empty<SelectListItem>(), "TestId", "TestName"), new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.TestId, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            <div class="form-check">
                <label class="form-check-label" for="invalidCheck2">
                    Is First Round ?
                </label>
                @Html.CheckBox("isFirstRound", false, new { @style = "margin-left:10px" })
            </div>
        </div>
        <div class="form-group"> 
            <div class="form-check">
                <label class="form-check-label" for="invalidCheck2">
                    Coding Challenge Report
                </label>
                <input type="file" id="dataFile" name="upload" />
            </div>
        </div>
        <div class="form-group">
            <input type="submit" value="Upload" class="btn btn-success" />
        </div>
    </div>
    }
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $.getJSON("/Recruitments/List",
            function (classesData) {
                var select = $("#RecruitmentId");
                select.empty();
                select.append($('<option/>', {
                    value: 0,
                    text: "Select a Recruitments"
                }));
                $.each(classesData, function (index, itemData) {
                    select.append($('<option/>', {
                        value: itemData.RecruitmentID,
                        text: itemData.Name
                    }));
                });
            });
        //$.getJSON("/TestsHosted/List",
        //    function (classesData) {
        //        var select = $("#TestId");
        //        select.empty();
        //        select.append($('<option/>', {
        //            value: 0,
        //            text: "Select a Tests"
        //        }));
        //        $.each(classesData, function (index, itemData) {
        //            select.append($('<option/>', {
        //                value: itemData.TestId,
        //                text: itemData.TestName
        //            }));
        //        });
        //    });
        $("#RecruitmentId").change(function () {
            $.getJSON("/TestsHosted/List?RecruitmentId=" + $(this).val(),
                function (classesData) {
                    var select = $("#TestId");
                    select.empty();
                    select.append($('<option/>', {
                        value: 0,
                        text: "Select a Tests"
                    }));
                    $.each(classesData, function (index, itemData) {
                        select.append($('<option/>', {
                            value: itemData.TestId,
                            text: itemData.TestName
                        }));
                    });
                });
        });
    });
</script>